apiVersion: apps/v1
kind: Deployment
metadata:
  name: app4
  labels:
    app: app4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app4
  template:
    metadata:
      labels:
        app: app4
    spec:
      containers:
      - name: app4
        image: neeranuchj/kubernetes-zerotrust:internal-api-service-2
        ports:
        - containerPort: 5002
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "250Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: app4
spec:
  selector:
    app: app4
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
  type: ClusterIP
