version: '3.7'

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - kcnet
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      timeout: 5s

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: always
    environment:
      - KEYCLOAK_HTTPS_CERT_FILE=/etc/ssl/certs/server.crt
      - KEYCLOAK_HTTPS_KEY_FILE=/etc/ssl/private/server.key
      - KEYCLOAK_HOSTNAME=sso.neeranuchj.org
      - KEYCLOAK_HOSTNAME_STRICT=false
      - DB_VENDOR=postgres
      - DB_ADDR=db:5432 
      - DB_DATABASE=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./server.crt:/etc/ssl/certs/server.crt
      - ./server.key:/etc/ssl/private/server.key
    ports:
      - "8443:8443"
    extra_hosts:
      - "sso.neeranuchj.org:127.0.0.1"
    command: ["start", "--https-port", "8443", "--https-certificate-file", "/etc/ssl/certs/server.crt", "--https-certificate-key-file", "/etc/ssl/private/server.key", "--hostname-strict=false"]
    networks:
      - kcnet
    depends_on:
      db:
        condition: service_healthy 

  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./server.crt:/etc/ssl/certs/server.crt
      - ./server.key:/etc/ssl/private/server.key
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - keycloak
    networks:
      - kcnet

networks:
  kcnet:
    driver: bridge

volumes:
  dbdata:
  caddydata:
  caddyconfig: