version: '3.7'

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - kcnet

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: sso-keycloak
    restart: always
    environment:
      - KEYCLOAK_HTTPS_CERT_FILE=/etc/ssl/certs/server.crt
      - KEYCLOAK_HTTPS_KEY_FILE=/etc/ssl/private/server.key
    volumes:
      - ./server.crt:/etc/ssl/certs/server.crt
      - ./server.key:/etc/ssl/private/server.key
    ports:
      - "8443:8443"
    command: ["start", "--https-port", "8443", "--https-certificate-file", "/etc/ssl/certs/server.crt", "--https-certificate-key-file", "/etc/ssl/private/server.key"]
    networks:
      - kcnet

  caddy:
    image: caddy:2
    container_name: sso-caddy-1
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./server.crt:/etc/ssl/certs/server.crt
      - ./server.key:/etc/ssl/private/server.key
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - keycloak
    networks:
      - kcnet

networks:
  kcnet:
    driver: bridge

volumes:
  dbdata:
  caddydata:
  caddyconfig:
