services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks: [kcnet]

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: unless-stopped
    depends_on: [db]
    environment:
      KEYCLOAK_ADMIN: ${KC_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_DB_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_PROXY: edge
    command: ["start"]
    expose:
      - "8080"
    networks: [kcnet]

  caddy:
    image: caddy:2
    restart: unless-stopped
    depends_on: [keycloak]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddydata:/data
      - caddyconfig:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks: [kcnet]

networks:
  kcnet:

volumes:
  dbdata:
  caddydata:
  caddyconfig:
