apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: {name: kube-oidc-proxy-impersonator}
rules:
- apiGroups: [""]
  resources: ["users","groups","serviceaccounts"]
  verbs: ["impersonate"]
- apiGroups: ["authentication.k8s.io"]
  resources: ["userextras/*"]
  verbs: ["impersonate"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: {name: kube-oidc-proxy-impersonator}
subjects:
- kind: ServiceAccount
  name: kube-oidc-proxy
  namespace: auth-proxy
roleRef:
  kind: ClusterRole
  name: kube-oidc-proxy-impersonator
  apiGroup: rbac.authorization.k8s.io